<a href="https://colab.research.google.com/github/Dk8976/College-Practical/blob/main/Data-Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
print("x3 ndim: ", x3.ndim)#dimension
print("x3 shape:", x3.shape)#shape
print("x3 size: ", x3.size)#size
print("dtype:", x3.dtype)#datatype
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
print(x1)
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])
print(x2)
print(x2[0,0])
print(x2[2,0])
print(x2[2,-1])
x2[0,0]=12
print(x2[0,0])
x1[0]=3.14159
print(x1[0])


[5 0 3 3 7 9]
5
7
9
7
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
1
7
12
3


In [ ]:
import numpy as np
x=np.arange(10)
print(x)
print(x[:5])
print(x[5:])
print(x[4:7])
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[5::-2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [ ]:
x2 = np.random.randint(10, size=(3, 4))
print(x2)
print(x2[:2, :3])
print(x2[:3, ::2])
print(x2[::-1, ::-1])
print(x2[:, 0])
print(x2[0, :])
print(x2[0])
x2_sub = x2[:2, :2]
print(x2_sub)
x2_sub[0, 0]=99
print(x2_sub)
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)



[[5 9 3 0]
 [5 0 1 2]
 [4 2 0 3]]
[[5 9 3]
 [5 0 1]]
[[5 3]
 [5 1]
 [4 0]]
[[3 0 2 4]
 [2 1 0 5]
 [0 3 9 5]]
[5 5 4]
[5 9 3 0]
[5 9 3 0]
[[5 9]
 [5 0]]
[[99  9]
 [ 5  0]]
[[99  9]
 [ 5  0]]
[[42  9]
 [ 5  0]]


In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])
# row vector via reshape
x.reshape((1, 3))


array([[1, 2, 3]])

In [ ]:
x[np.newaxis, :]



array([[1, 2, 3]])

In [ ]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [ ]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])


In [ ]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])


In [ ]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

y = np.array([[99],[99]])
np.hstack([grid, y])


In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)


[1 2 3] [99 99] [3 2 1]


In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)


[[9 8 7]
 [6 5 4]]
[]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)



[[9 8]
 [6 5]]
[[7]
 [4]]


In [ ]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5) #Addition
print("x - 5 =", x - 5)# Subtraction	
print("x * 2 =", x * 2)#Multiplication
print("x / 2 =", x / 2)#division
print("x // 2 =", x // 2) # floor division
print("-x = ", -x)#negation
print("x ** 2 = ", x ** 2)#power
print("x % 2 = ", x % 2)#modulus
np.absolute(x)#absolute


x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


array([0, 1, 2, 3])

In [ ]:
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))


theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [ ]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))#exponent
print("2^x =", np.exp2(x))#exponent of 2
print("3^x =", np.power(3, x))
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))


x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [ ]:
from scipy import special
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))


gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [ ]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))



erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)


[ 0. 10. 20. 30. 40.]


In [ ]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)



[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [ ]:
x = np.arange(1, 6)

In [ ]:
np.add.reduce(x)#reduce

15

In [ ]:
np.multiply.reduce(x)


120

In [ ]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [ ]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [ ]:
x = np.arange(1, 6)
np.multiply.outer(x, x)


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [ ]:
import numpy as np
L = np.random.random(100)
sum(L)
min(big_array), max(big_array)
np.min(big_array), np.max(big_array)
%timeit min(big_array)
%timeit np.min(big_array)
print(big_array.min(), big_array.max(), big_array.sum())


NameError: ignored

In [2]:
import numpy as np
M = np.ones((2, 3))
a = np.arange(3)
M + a


array([[1., 2., 3.],
       [1., 2., 3.]])

In [3]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a + b


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [4]:
a[:, np.newaxis].shape


(3, 1, 1)

In [7]:
M + a[:,np.newaxis]
x = np.array([1, 2, 3, 4, 5])
x < 3 # less than


array([ True,  True, False, False, False])

In [9]:
x > 3 # greater than

array([False, False, False,  True,  True])

In [10]:
x <= 3 # less than or equal

array([ True,  True,  True, False, False])

In [11]:
x >= 3 # greater than or equal

array([False, False,  True,  True,  True])

In [12]:
x != 3 # not equal

array([ True,  True, False,  True,  True])

In [14]:
x == 3 # equal

array([False, False,  True, False, False])

In [15]:
np.count_nonzero(x < 6)#count

5

In [16]:
np.any(x > 8) 

False

In [17]:
np.any(x < 0)


False

In [19]:
# are all values less than 10?
np.all(x < 10)


True

In [20]:
# are all values equal to 6?
np.all(x == 6)


False

In [21]:
import numpy as np
import pandas as pd
# use Pandas to extract rainfall inches as a NumPy array
rainfall = pd.read_csv('data/Seattle2014.csv')['PRCP'].values
inches = rainfall / 254 # 1/10mm -> inches
inches.shape(365,)

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set() # set plot styles
plt.hist(inches, 40);
np.sum((inches > 0.5) & (inches < 1))


FileNotFoundError: ignored